name: Lint
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 16.x
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: yarn install
      run: yarn install

    - name: Lint
      run: yarn run format-check
